spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 13.124.74.82:9092
                    zkNodes: 13.124.74.82:2181
            function:
                definition: orderMessageResult;
            bindings :
                orderMessage :
                    destination : orderMessage-topic
                orderMessageResult-in-0:
                    destination : orderMessageResult-topic
            poller:
                fixed-delay: 500000